feat: save selection
terrestris/shogun-demo-client pull request #176
Opened 2022-07-12 15:38 UTC by FritzHoing

a Modal has been created, that gets the link of the current Map.

For now:
Additional WMS-Layers are not included in that link. WIP.

2022-07-19 11:34 UTC, Unraveler requested changes
You should fix the warnings displayed here. Otherwise, it looks good to me.

2022-07-19 12:34 UTC, dnlkoch requested changes
Thanks @FritzHoing!

I noted some minor remarks and as @Unraveler stated already, please check the linter warning.

2022-07-19 12:34 UTC, dnlkoch commented on src/components/SaveSelectModal/SaveSelectModal.tsx
> +
```suggestion
```

2022-07-19 12:34 UTC, dnlkoch commented on src/components/SaveSelectModal/SaveSelectModal.tsx
> +  function onCopyClick() {
Please convert to arrow function.

2022-07-19 12:34 UTC, dnlkoch commented on src/components/SaveSelectModal/SaveSelectModal.tsx
> +  function link() {
Please convert to arrow function.

2022-07-19 12:34 UTC, dnlkoch commented on src/components/SaveSelectModal/SaveSelectModal.tsx
> +};
```suggestion
};

```

2022-07-19 12:34 UTC, dnlkoch commented on src/hooks/useQueryParams.ts
> + */
```suggestion
```

2022-07-19 12:34 UTC, dnlkoch commented on src/components/SaveSelectModal/SaveSelectModal.tsx
> +export default SaveSelectModal;
I would prefer to have this component renamed to something like `PermalinkModal` or similar.

2022-07-20 11:43 UTC, dnlkoch requested changes

2022-07-20 11:43 UTC, dnlkoch commented on src/components/PermalinkModal/index.tsx
> +export default SharePanel;
The file should be renamed accordingly.

2022-07-20 11:43 UTC, dnlkoch commented on src/components/PermalinkModal/index.tsx
> +  const mailBody = `Hey,\r\nsieh dir an was ich im Geoportal Raumordnung Baden-Württemberg gefunden habe:\r\n${link}`;
This should be adjusted.

2022-07-20 11:43 UTC, dnlkoch commented on src/components/PermalinkModal/index.tsx
> +    const whatsAppUrl = new URL('http://wa.me');
```suggestion
    const whatsAppUrl = new URL('https://wa.me');
```

Untested.

2022-07-20 11:43 UTC, dnlkoch commented on src/i18n/translations.ts
> +        saveSelection: 'Save selection'
Is this still used?

2022-07-20 15:10 UTC, dnlkoch approved these changes

2022-07-20 15:11 UTC, merged