feat(draw): added draw component and translations
terrestris/shogun-demo-client pull request #194
Opened 2022-07-19 10:56 UTC by Unraveler

Added Draw Tool to Tools menu:
Now it's possible to draw a point, a line, a polygon, a circle, a rectangle and write annotations.
Not persistent

Please review @terrestris/devs

2022-07-19 11:06 UTC, dnlkoch requested changes
Some files seem to be missing in the PR.

2022-07-19 11:15 UTC, Unraveler commented
Added missing files

2022-07-19 12:38 UTC, dnlkoch reviewed
Very nice @Unraveler!

Can we also include a button for modifying an existing geometry? And would it be possible to create a import/export functionality (e.g. via a GeoJSON file)?

2022-07-19 12:38 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +
```suggestion
```

2022-07-19 12:38 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +      <DrawButton
```suggestion

      <DrawButton
```

2022-07-19 17:54 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +          // @ts-ignore
Any chance to get rid of this?

2022-07-19 17:54 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +  const onGeoJSONUpload = (geoJSONFile: any ) => {
Please specify the correct type.

2022-07-19 17:54 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +    const type = geoJSONFile.type !== 'application/geojson' ? geoJSONFile.type : 'NOT SUPPORTED';
Looks quite complicated to me, we might want to check for the supported type only an return if an unsupported one has been handed over.

2022-07-19 17:54 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +      alert('NOT SUPPORTED');
See comment above.

2022-07-19 17:54 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +      var fileReader=new FileReader();
```suggestion
      const fileReader = new FileReader();
```

2022-07-19 17:54 UTC, dnlkoch commented on src/components/ToolMenu/Draw/index.tsx
> +          feat.getGeometry()?.transform('EPSG:4326', 'EPSG:3857');
GeoJSON should be EPSG:4326 always and we nigjt want to get the current projection from the map/view here.

2022-07-20 08:24 UTC, LukasLohoff commented on src/components/ToolMenu/Draw/index.tsx
> +    var fileReader=new FileReader();
```suggestion
    const fileReader = new FileReader();
```

2022-07-20 08:31 UTC, LukasLohoff commented
Looks good! Left some minor comments together with @dnlkoch 

What do you think about an export button? maybe that's an option for a follow-up MR.

2022-07-20 08:31 UTC, LukasLohoff approved these changes

2022-07-20 09:56 UTC, merged